[env]
framework = arduino
lib_deps = file://../../../DomoticsCore-Core/
lib_archive = false
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=3
extra_scripts = pre:../../../clean_examples.py

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32dev
build_flags = ${env.build_flags} -std=gnu++14
build_unflags = -std=gnu++11
monitor_filters = esp32_exception_decoder

[env:esp8266dev]
platform = espressif8266
board = d1_mini
build_flags = ${env.build_flags} -std=gnu++17

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags = -std=gnu++11
